project:
  type: website
  output-dir: docs

website:
  title: "ODP Style & Standards (Draft)"
  navbar:
    search: true
    collapse: true
    right:
      - href: index.qmd
        text: Home
      - href: dataset-style.qmd
        text: Dataset Style
      - href: metadata-style.qmd
        text: Metadata Style
      - href: metadata-standards.qmd
        text: Metadata Standards
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/lsheble/style-guide
          - text: Report a Bug
            href:  https://github.com/lsheble/style-guide/issues

format:
  html:
    theme: 
      - cosmo
      - cod-style.scss
    css: styles.css
    toc: true

editor: visual

